version: "3.2"
services: 
    grpcbackend:
        hostname: grpcbackend
        build: backend/.
        # ports:
        #     # - "8080:8080"
        #     # - "9000:9000"
        networks:
            - backend
        links: 
            - redis
        depends_on: 
            - redis

    redis:
        image: "redis:alpine"
        command: redis-server --requirepass P@ssword
        networks: 
            - backend

    #
    #   Running in container with docker-compose is causing some CORS issue (TODO: Fix)
    #
    frontend:
        hostname: frontend
        build: frontend/.
        ports:
            - "1234:1234"
            - "3000:3000"
        networks:
            - backend
        links:
            - grpcbackend

networks:
    backend:
        driver: bridge