version: "3.2"
services: 
    grpcbackend:
        build: backend/.
        # ports:
            # - "8080:8080"
            # - "9000:9000"
        networks:
            - backend
        links: 
            - redis

    redis:
        image: "redis:alpine"
        command: redis-server --requirepass P@ssword
        networks: 
            - backend

    frontend:
        build: frontend/.
        ports:
            - "1234:1234"
            - "3000:3000"
        networks:
            - backend
        links:
            - grpcbackend

networks:
    backend:
        driver: bridge