version: "3.2"
services: 
    grpcbackend:
        build: backend/.
        ports:
            - "8080:8080"
            - "9000:9000"
        networks:
            - backend
        links: 
            - redis
            # - frontend
        depends_on: 
            - redis

    redis:
        image: "redis:alpine"
        command: redis-server --requirepass P@ssword
        networks: 
            - backend

    #
    #   Running in container is causing some CORS issue (TODO: Fix)
    #
    # frontend:
        # domainname: 
            # - "frontend.local"
        # build: frontend/.
        # ports:
            # - "1234:1234"
            # - "3000:3000"
        # networks:
            # - backend

networks:
    backend:
        driver: bridge