version: "3.2"
services: 
    grpc_server:
        build: backend/.
        ports: 
            - "9000:9000"
            - "8080:8080"
        networks:
            - backend
        links: 
            - redis

    redis:
        image: "redis:alpine"
        command: redis-server --requirepass P@ssword
        networks: 
            - backend

networks:
    backend:
        driver: bridge