version: "3.2"
services: 
    grpcbackend:
        hostname: grpcbackend
        build: backend/.
        networks:
            - backend
        links: 
            - redis
        depends_on: 
            - redis

    redis:
        image: "redis:alpine"
        command: redis-server --requirepass P@ssword
        networks: 
            - backend

        
    frontend:
        hostname: frontend
        build: frontend-go/.
        ports:
            - "8081:8081"
        networks:
            - backend
        links:
            - grpcbackend

networks:
    backend:
        driver: bridge