version: "3.2"
services: 
    grpc_server:
        build: backend/.
        ports: 
            - "9000:9000"
        networks:
            - backend
        links: 
            - redis

    redis:
        image: "redis:alpine"
        command: redis-server
        environment: 
            - ALLOW_EMPTY_PASSWORD=yes 
        networks: 
            - backend

networks:
    backend:
        driver: bridge